### PR TITLE
Random Forest Model

### LINKED ISSUE #14: Building Random Forest model
Your task is to model each of TFIDF and Word2Vec with Random Forest

### PR DESCRIPTION
**Pull request by ForChune**

### CODE REVIEW

**Comment by olaidejoseph** [comment]
Good work Fortune.

**Review by sharonibejih — APPROVED** [review]
Let's merge this. This is good. Thanks Fortune.

**Comment by Jolomi-Tosanwumi** [comment]
Nice one Fortune. But it seem you created a branch for your work instead of creating it in your forked repo. I am merging it but next time, we are to create our work in our forked repo.

**Comment by ForChune** [comment]
> Nice one Fortune. But it seem you created a branch for your work instead of creating it in your forked repo. I am merging it but next time, we are to create our work in our forked repo.

Okay, thanks Jolomi, note taken. Initially, I made the pull request from my forked repo, however, I couldn't get the names of reviewers, hence my decision to make the pull request by creating a branch on the base repo

**Pull request merged**
