### PR TITLE
adding EDA and oversampling notebooks

### PR DESCRIPTION
**Pull request by Jolomi-Tosanwumi**
Adding EDA and oversampling notebooks in EDA_and_preprocessing folder.

Find the link to the EDA notebook [here](https://github.com/Jolomi-Tosanwumi/stage-f-06-wine-tasting/blob/master/EDA_and_preprocessing/EDA_wine_tasting.ipynb)

Find the link to the oversampling notebook [here](https://github.com/Jolomi-Tosanwumi/stage-f-06-wine-tasting/blob/master/EDA_and_preprocessing/Oversampling_preprocessing.ipynb)

### CODE REVIEW

**Review by sharonibejih — APPROVED** [review]
This is very good and detailed. For me, it's okay to merged.

**Review by ForChune — APPROVED** [review]
Like @sharonibejih  said, good job @Jolomi-Tosanwumi. You've covered different scenarios of the analysis in a very detailed manner. I'm approving this request.

**Review by Adeola23 — APPROVED** [review]
This is very detailed @Jolomi-Tosanwumi

**Review by Jahfaith — APPROVED** [review]
Weldon bro.

**Comment by ShashankSubham** [comment]
Great work bud!

**Pull request merged**
