### PR TITLE
Did word2vec embedding

### PR DESCRIPTION
**Pull request by Jolomi-Tosanwumi**
Word2Vec embedding was used as a preprocessing strategy in word2vec-wine-review.ipynb notebook in the EDA_and_preprocessing folder.

Find the notebook [here](https://github.com/Jolomi-Tosanwumi/stage-f-06-wine-tasting/blob/master/EDA_and_preprocessing/word2vec-wine-review.ipynb)

### CODE REVIEW

**Comment by Jolomi-Tosanwumi** [comment]
I am closing this pull request now, because the name of the country US would be same as first person plural 'us'. Also want to confirm the dexterity of our word2vec model by checking if some word2vec magic like' king - man + woman = queen' will be true. Will reopen it after effecting these changes.

**Comment by Jolomi-Tosanwumi** [comment]
Renamed US to United States of America because after converting to lower case, US would be same as first person plural 'us'. Also did some word2vec magic analogous to king - man + woman = queen that confirmed the dexterity of our word2vec model.

**Comment by mentor-mide** [comment]
Nice,  the score for this model with word2vec improved from what we had the last time

**Comment by ForChune** [comment]
Very thorough and detailed work @Jolomi-Tosanwumi. Thumbs up!

**Pull request merged**
